version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
   install:
      - requirements: docs/requirements-rtd.txt
      # no - method: pip here, -e . is already in docs/requirements-rtd.txt
