version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

python:
   install:
      - requirements: docs/requirements-rtd.txt
      # no - method: pip here, -e . is already in docs/requirements-rtd.txt
